import './dashboard';
import './goodsReceiving';
import './shelving';
import './productLocator';
import './catalog';
import './definitions';
import './orders';
import './boxDefinitions';
import './orderTracking';
